package generator.panels;

import generator.extenders.RandomiserInstance;
import generator.extenders.RandomiserPanel;

import java.util.LinkedHashMap;

import javax.swing.JOptionPane;

public class PanelPartialDuplicateFieldRandomiser extends RandomiserPanel{
	/*
	 * dgMaster: A versatile, open source data generator.
	 *(c) 2007 M. Michalakopoulos, mmichalak@gmail.com
	 */

		private static final long serialVersionUID = 8797054440294377030L;
		/** Creates new form PanelSequencer */
	    public PanelPartialDuplicateFieldRandomiser()
	    {
	        initComponents();
	    }
	    
	    
	    public void initialise(RandomiserInstance ri)
	    {
	        txtName.setText( ri.getName() );
	        txtDescription.setText( ri.getDescription() );
	        
	        String start, end, col;
	        LinkedHashMap<String,String> hashMap;
	        
	        hashMap = ri.getProperties();
	        start  = (String) hashMap.get("startPos");
	        end  = (String) hashMap.get("endPos");
	        col = (String) hashMap.get("columnNum");
	        
	        startingPosition.setValue(Integer.parseInt(start));
	        endingPosition.setValue(Integer.parseInt(end));
	        columnPosition.setValue(Integer.parseInt(col));
	    }
	     
	    
	    public RandomiserInstance getRandomiserInstance()
	    {
	        String name, description;
	        Integer startingPos, endingPos, columnNum;        
	        LinkedHashMap<String,String> hashMap = new LinkedHashMap<String,String>();
	        RandomiserInstance ri = new RandomiserInstance();
	        
	        //get field values
	        name = txtName.getText().trim();
	        description  = txtDescription.getText().trim();
	        startingPos = (Integer) startingPosition.getModel().getValue();
	        endingPos = (Integer) endingPosition.getModel().getValue();
	        columnNum = (Integer) columnPosition.getModel().getValue();
	        
	        //create the hashmap
	        hashMap.put("startPos",startingPos.toString());
	        hashMap.put("endPos",endingPos.toString());
	        hashMap.put("columnNum",columnNum.toString());
	      
	        
	        ri.setRandomiserType("PartialDuplicateFieldRandomiser");
	        ri.setName(name);
	        ri.setDescription(description);
	        ri.setProperties(hashMap); 
	                
	        return ri;
	    }
	    
	  
	    public boolean isFormValid()
	    {
	        String name;
	        Integer nullField;
	        //get field values
	        name = txtName.getText().trim();
	       // nullField = (Integer) endingPosition.getModel().getValue();
	               
	        //run checks
	        if(name.length()==0)
	        {
	            JOptionPane.showMessageDialog(this,"Please provide a value for the name.","Required field",JOptionPane.ERROR_MESSAGE); 
	            return false;
	        }        
	        return true;
	    }

	    
	    
	    
	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jPanel2 = new javax.swing.JPanel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        txtName = new javax.swing.JTextField();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        txtDescription = new javax.swing.JTextArea();
	        jPanel1 = new javax.swing.JPanel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        startingPosition = new javax.swing.JSpinner();
	        endingPosition = new javax.swing.JSpinner();
	        columnPosition = new javax.swing.JSpinner();

	        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Case description"));

	        jLabel4.setText("Name:");

	        jLabel5.setText("Description:");

	        txtDescription.setColumns(20);
	        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
	        txtDescription.setLineWrap(true);
	        txtDescription.setRows(5);
	        txtDescription.setWrapStyleWord(true);
	        jScrollPane1.setViewportView(txtDescription);

	        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel2Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
	                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                    .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
	                .addContainerGap())
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel2Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(jLabel4)
	                    .add(txtName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                    .add(jLabel5)
	                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
	                .addContainerGap())
	        );

	        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Percentages of generated values"));

	        jLabel3.setText("Starting Position:");

	        jLabel2.setText("Ending Position:");

	        jLabel6.setText("Column Number");
	        
	        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
	                    .add(jLabel3)
	                    .add(jLabel2)
	                    .add(jLabel6))
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
	                    .add(startingPosition)
	                    .add(endingPosition, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
	                    .add(columnPosition))
	                .addContainerGap())
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(jLabel3)
	                    .add(startingPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(jLabel2)
	                    .add(endingPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(jLabel6)
	                    .add(columnPosition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                )
	                
	       
	        );

	        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
	                .addContainerGap()
	                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
	                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
	                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	    }// </editor-fold>//GEN-END:initComponents
	    
	    
	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JSpinner startingPosition;
	    private javax.swing.JSpinner endingPosition;
	    private javax.swing.JSpinner  columnPosition;
	    private javax.swing.JTextArea txtDescription;
	    private javax.swing.JTextField txtName;
	    // End of variables declaration//GEN-END:variables

}
