package generator.masterbuild;

import generator.stagebuild.StageBuilderConfig;

/**
 * @See MasterBuilder application.properties
 * @author joaoesteves
 *
 */
public class BuilderProps {
	/**
	 * build order: stage ordered:  time ordered
	 */
	public static final String DGMASTER_MASTERBUILD_BUILDORDER = "dgmaster.masterbuild.buildorder";

	/**
	 * Number of data days to be generated by master builder
	 */
	public static final String DGMASTER_MASTERBUILD_NUMBER_OF_DAYS = "dgmaster.masterbuild.number.of.days";

	/**
	 * Start date for the period that's going to be generated by masterBuilder
	 */
	public static final String DGMASTER_MASTERBUILD_START_DATE = "dgmaster.masterbuild.start.date";

	/**
	 * Total number of stages
	 */
	public static final String DGMASTER_MASTERBUILD_NUMSTAGES = "dgmaster.masterbuild.numstages";

	/**
	 * Master builder root configuration system definitions
	 */
	public static final String DGMASTER_MASTERBUILD_DEFAULT_SYSTEMDEFINITIONS = "dgmaster.masterbuild.default.systemdefinitions";

	/**
	 * dir for shared configurations between stages
	 */
	public static final String DGMASTER_MASTERBUILD_SHAREDEDIR = "dgmaster.masterbuild.sharededir";

	/**
	 * base dir for all the stage folders
	 */
	public static final String DGMASTER_MASTERBUILD_STAGEBASEDIR = "dgmaster.masterbuild.stagebasedir";

	/**
	 * master builder root configuration log4j filename
	 */
	public static final String DGMASTER_MASTERBUILD_LOG4J_CONFIG = "dgmaster.masterbuild.log4j.config";

	/**
	 * master builder root dir
	 */
	public static final String DGMASTER_MASTERBUILD_BASEDIR = "dgmaster.masterbuild.basedir";
	
	/**
	 * stage specific properties file
	 * @see StageBuilderConfig
	 */
	public static final String DGMASTER_MASTERBUILD_STAGEPROPERTIESFILE = "dgmaster.masterbuild.stagepropertiesfile.";

	/**
	 * dir name for the specific stage.
	 */
	public static final String DGMASTER_MASTERBUILD_STAGEDIR = "dgmaster.masterbuild.stagedir.";

	/**
	 * Class name associated with the specific stage
	 */
	public static final String DGMASTER_MASTERBUILD_STAGEBUILDER = "dgmaster.masterbuild.stagebuilder.";
	
	public static final String DGMASTER_MASTERBUILD_KEYSTAGE = "dgmaster.masterbuild.KeyStage";
	
	public static final String DGMASTER_MASTERBUILD_KEYSTAGEABSOLUTENUMBER = "dgmaster.masterbuild.KeyStageAbsoluteNumber";
	
	public static final String  DGMASTER_MASTERBUILD_ENTITYEVENTMODELFILEDIR = "dgmaster.masterbuild.EntityEventModelFile";

		
}
